### ISSUE TITLE
Git install should not create icons by default - breaks install by System account

### ISSUE THREAD

**Issue by ferventcoder** [ferventcoder/chocolatey-packages#103]
See https://github.com/git-for-windows/git/issues/570 for details.

**Comment by ferventcoder** [comment]
@DarwinJS over here mate.

**Comment by ferventcoder** [comment]
@DarwinJS said:

>I hate to ask this :( - is there any chance to change my chocolatey ID from Darwin_CSIWindowscom to DarwinJS ?

It can be changed.

> If not, no problem - please add Darwin_CSIWindowscom to chocolatey maintainers and DarwinJS (github) to chocolatey source for relevant git choco packages.

That's really not the idea. It gets fixed in this source and then gets pushed out from here.

**Comment by ferventcoder** [comment]
> Rob - could use a few pointers on how to get started - *) choco source, *) whether you want me to update the choco source directly - if not, what is the procedure to follow to submit my source, *) whether you want me to update the choco package directly.

Here is the source, already linked it to the other issue awhile back.

**Comment by ferventcoder** [comment]
@DarwinJS your username has been changed.

**Comment by DarwinJS** [comment]
Thanks!

If I understand correctly you want me to fork the repository on your chocolatey packages, fix and test the package and then do a pull request?

If that's not it - please let me know.

If there is a guide for how to do this with the choco team I would love to see it as I also wanted to contribute to the choco PS1 modules as well.

**Comment by ferventcoder** [comment]
Yep, that's the standard Github contribution workflow. Fork and Pull.

**Comment by DarwinJS** [comment]
Rob,
Apologies for my ignorance here.

The packages under "automatic" are tokenized and I cannot cpack them directly to test.

Is there a way to cpack just that one package or should I just make identical changes to the source from the git.install .nupkg, then test that, then make the changes to automatic folder and do a pull request?

D.

**Comment by ferventcoder** [comment]
@DarwinJS no worries, you are right, this should probably have a guide for that - head over to the _output folder and find git.install.

**Comment by DarwinJS** [comment]
I'm a bug magnet.

So my very first test is on a machine that has an existing git install and I can see by the choco output my command line has been fixed up perfectly.

FAIL.  Why?  Because HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Git_is1\Inno Setup: Selected Components contains "icons\quicklaunch" from a previous run.

I am very tempted to make this work in all circumstances - including forced reinstall - by removing "icons\quicklaunch" from that key if found.

Any thoughts or guidance on that?

**Comment by ferventcoder** [comment]
Haha. 

So don't remove it. Just remember that it would not have been there on a good install.

**Comment by ferventcoder** [comment]
Unless you are stating that it was already there even with the failed install.

**Comment by DarwinJS** [comment]
Rob - which file do I change when I submit to you?  Just automatic, just _output or both?

D.

**Comment by ferventcoder** [comment]
both, but if you just want to change the one in _output, consider that the package version will need updated and use our package fix version notation. Man, yes, this needs some documentation on how to submit fixes. :/

**Comment by DarwinJS** [comment]
Rob - it looks like adding innosetup's '/suppressmessageboxes' for all installs with git.install would help prevent these hangs due to a message box being displayed while in SYSTEM context.  It would also help in any other headless deployments.

On locked files, it will fail the install (unless changes are made to the innosetup), but I think at least we'll get back an proper exit code to chocolatey rather than an eternal hang.

I strongly recommend adding '/suppressmessageboxes' to *all* installs.  There are automation situations that  would still hang - for example: using remoting to run the chocolatey package - still no UI, so a message box will hang.  

However, if you wish I could limit it to adding that option when running under SYSTEM.  

I am going to add a recommendation to the git team thread to also use  the "restartreplace" option on all their entries under [files] as in the below article.  The article also discusses '/suppressmessageboxes'

http://stackoverflow.com/questions/26480722/inno-setup-how-can-i-suppress-files-in-use-dialog-when-install-silently

**Comment by ferventcoder** [comment]
We pulled the suppressmessageboxes at one point. It may be a good idea to bring it back. The reason we pulled it is described in more detail in that original thread.

**Comment by DarwinJS** [comment]
OK some follow up stuff here:
[DONE] I figured out all the discussion about ssh-agent preventing the git install was for the copy it has within git's own folders.  I now detect if any instances of *the specific ssh-agent in the git folder* are running and terminate them and put a message to the console.

[OPPS] I was wrong about the install re-reading the uninstall key - just didn't have my removal of the offending option working correctly.

[QUESTION] I think we should use inno setup's /RESTARTEXITCODE=3010 and then trap for this condition and put a note on the screen and or log that a restart is required.  Then if git team takes my recommendation to change the behavior so the installer queues up locked file writes for reboot, the choco package will respond intelligently.  OK to do that?  If so, can you let me know a choco example of this?  I am thinking to NOT put 3010 on valid exit codes then wrap install-chocolateypackage in a try catch and if the code is 3010 give a success and a message?  But a code sample of however it needs to happen would save a lot of time.  FYI - due to the code added for ssh-agent, this will NOT happen for the very frequent occurrence of ssh-agent locking the install.

**Comment by ferventcoder** [comment]
I was not aware InnoSetup had a restart exit code? https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/domain/InnoSetupInstaller.cs#L29-L44

**Comment by ferventcoder** [comment]
As a package manager, chocolatey does not handle reboots. It effectively blocks them.

**Comment by DarwinJS** [comment]
From the docs it appears you have to pass it the return code you want back if a restart is required - otherwise it does zero even for restart required.  Doc'd here: http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline

Yes I understand not to reboot, but was planning to note it on screen and possibly the choco log.

**Comment by DarwinJS** [comment]
Should I skip /RESTARTEXITCODE=3010 for now if there is inno setup specific code in chocolatey then?

**Comment by ferventcoder** [comment]
perhaps file it as a followup issue?

**Comment by DarwinJS** [comment]
I modified both automatic and _output copies with exact same changes.

I created my own sub ..\automatic\_output\git.install\2.6.4.20151216 and then realized maybe you didn't intend me to do that because you won't easily be able to see diffs in git.  Let me know if you want me to make the changes to ..\_output\git.install\2.6.4 instead (with my new version in the nuspec of course.

I haven't committed yet - so haven't created any messes... yet ;)

D.

**Comment by ferventcoder** [comment]
Creating the new version is exactly what I'd hoped for.

**Comment by DarwinJS** [comment]
Just did a pull request.  

Realized I left an unnecessary  -validexitcodes on the call to Install-ChocolateyPackage in the output folder.

**Comment by ferventcoder** [comment]
This is fixed I believe.
