### ISSUE TITLE
Scheme for HTTP urls

### ISSUE THREAD

**Issue by ekrengel** [ferventcoder/chocolatey-packages#158]
Now that chocolatey requires checksums, do you have a scheme for handling HTTP urls (such as in the tools\chocolateyInstall.ps1 for virtualbox)? Right now I'm passing '--allow-empty-checksums' as an option to chocolatey, but I'd like to help create a more secure patch.

**Comment by ferventcoder** [comment]
Thanks for creating an issue on this - I spent some time recently moving most things, at least in source, to https where applicable.

**Comment by ferventcoder** [comment]
Here's the progress so far

**Comment by ferventcoder** [comment]
Here's the progress so far - https://github.com/ferventcoder/chocolatey-packages/commit/7dd26f223ba637a283b2e005a96826749a24d631

**Comment by donneler** [comment]
Thanks! I am wondering if you have thought about what to do with packages that do not have an HTTPS url. In the case of virtualbox, my initial thought is to curl and then parse the checksums from (here)[https://www.virtualbox.org/download/hashes/5.1.2/SHA256SUMS]. And then use that checksum as an option passed to Install-ChocolateyPackage in the chocolateyInstall.ps1 script.

Right now I'm trying to figure out how you are generating the DownloadUrl, since I do not want to hardcode the parsing of the checksum to a specific virtualbox version.

**Comment by ferventcoder** [comment]
@donneler Were you talking about parsing those checksums as part of updating the package itself or as part of a runtime operation?

The one thing we definitely do not want is determining package checksums at runtime. They need to be static strings that are compiled with the package, so they are verified independently of the source location that could be compromised. If a download url is compromised, it's likely someone could also compromise those checksums. Because each package represents a version, it makes sense that that version will always have the same checksum.

Here's the original message to maintainers that contains a bit more detail - http://us8.campaign-archive1.com/?u=86a6d80146a0da7f2223712e4&id=b42c5e0150

**Comment by oifland** [comment]
@ferventcoder It would be part of updating the package. Virtualbox only has an HTTP download url for the .exe. It looks like Ketarin does not currently support getting checksums, at least by a quick read through the wiki and a glance over the source code. Did you have thoughts about how to handle cases where there's no HTTPS url for the msi/exe, but there's an HTTPS url for the checksum?

**Comment by ferventcoder** [comment]
@oifland right on. I just realized that the url for download is not while the rest of the site is, wow. That's a let down.

Anyway, Ketarin does support plugging in the ability to do things, such as checksumming. It's something that @dtgm does extensively with all of the packages that he maintains. It was linked in the above communication, but the link is https://github.com/dtgm/chocolatey-packages/blob/master/scripts/ketarin-settings-commands-02-afterupdatingapp.cs#L53. The trick is getting the instructions for doing so added to our wiki in a way that anyone can easily add it in.

The plans are to handle gathering checksums for all downloads, not just http. We run packages through VirusTotal, so those downloads are going to be independently verified. The checksums in the package will ensure that folks later on will get the same files that were verified and passed moderation.

**Comment by oifland** [comment]
Sorry, I'm a little new to how chocolately packages work on chocolatey.org. Are you using @dtgm's code to render the contents of this repo? I'm not seeing any custom scripts in here. I'd love to contribute something, but I'm not sure where to start.

The code linked above is downloading the exe/msi and [running the checksum locally](https://github.com/dtgm/chocolatey-packages/blob/master/scripts/ketarin-settings-commands-02-afterupdatingapp.cs#L54), but I was thinking of hitting the HTTPS url on virtualbox's site to confirm the checksum there. Maybe it would make sense to have a templated URL similar to the download URL to specify the checksum download URL?

**Comment by ferventcoder** [comment]
Closing this as most things are being or have been migrated over to the core community team repository - https://github.com/chocolatey/chocolatey-coreteampackages
