### ISSUE TITLE
(foobar2000) foobar2000 package fails

### ISSUE THREAD

**Issue by pascalberger** [ferventcoder/chocolatey-packages#162]
Installing foobar2000 fails since version 1.3.10:

```
foobar2000 v1.3.11 [Approved] - Possibly broken
Looking for alternative url
ERROR: Cannot index into a null array.
The upgrade of foobar2000 was NOT successful.
```

**Comment by pascalberger** [comment]
Seems like `$matches` is never set in the PowerShell module [here](https://github.com/ferventcoder/chocolatey-packages/blob/master/automatic/foobar2000/tools/Get-FilenameFromRegex.ps1#L38).

**Comment by ferventcoder** [comment]
$matches is a PowerShell magic variable.

**Comment by ferventcoder** [comment]
Like $errors

**Comment by welwood08** [comment]
I have a strong suspicion that visiting filehippo in a browser is the action I took before I noticed this had started working, though I'll wait until it starts failing again to confirm (unless someone else can check). If that's the case, filehippo is probably blocking the useragent used by Get-FilenameFromRegex until a non-blocked useragent from the same IP is used.

After the download succeeded I was getting errors about missing checksums not allowed for HTTP. Is there any reason this package doesn't just download directly from the official foobar2000 site which allows HTTPS?

**Comment by ferventcoder** [comment]
@welwood08 I think at the time this package was created it was set up a particular way due to some constraints with downloads from Foobar2000's site. Those restrictions may not be there anymore.

**Comment by welwood08** [comment]
I had another look at this today, I think the constraint you're referring to is that the official site only provides the latest version for download (so #168 would prevent installation of previous versions, if that's a concern).

Apart from missing checksum (which I know is a wider problem affecting many packages that is already well known), I have seen `choco install foobar2000` fail with the following errors so far:
- 1:
```
Looking for alternative url
ERROR: Cannot index into a null array.
The install of foobar2000 was NOT successful.
```
- 2:
```
Found URL that redirects to the download url: http://www.filehippo.com/download_foobar2000/69882/
ERROR: Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occurred on a receive."
The install of foobar2000 was NOT successful.
```
- 3:
```
Found URL that redirects to the download url: http://www.filehippo.com/download_foobar2000/69882/
Found secondary url that redirects to the download url: http://www.filehippo.com/en/download_foobar2000/download/29bc2e03c67daf77d245797e77d5d25a/
ERROR: Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occurred on a receive."
The install of foobar2000 was NOT successful.
```
- 4:
```
Found URL that redirects to the download url: http://www.filehippo.com/download_foobar2000/69882/
Found secondary url that redirects to the download url: http://www.filehippo.com/en/download_foobar2000/download/29bc2e03c67daf77d245797e77d5d25a/
Found download URL: http://www.filehippo.com/download/file/513c198ef434a176098e8a7ef475b6ecec90afe15499ba4e554f52520875c42b/
Downloading foobar2000
  from 'http://www.filehippo.com/download/file/513c198ef434a176098e8a7ef475b6ecec90afe15499ba4e554f52520875c42b/'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://www.filehippo.com/download/file/513c198ef434a176098e8a7ef475b6ecec90afe15499ba4e554f52520875c42b/'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: An unexpected error occurred on a receive."
The install of foobar2000 was NOT successful.
```

I also added a bit of debug output to the install script to discover that the error preceding `Looking for alternative url` in case 1 is also `Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occurred on a receive."`.

I observed in Fiddler and noticed 301 redirects to filehippo.com (non-www) before some of the failures. Modifying the URLs in the install script to avoid the redirects helps somewhat, but still isn't reliable. From what I can tell, filehippo has some sort of firewall that's abruptly closing connections whenever it feels like it (sometimes when a client follows a 301 redirect too quickly, or on the first request in a while, or I can't work out the pattern).

Aside: it looks like `ERROR: Cannot index into a null array.` is caused by exactly what @pascalberger suggested. The `$find` regex not matching because filehippo has changed the layout of the page with the 'latest' button, hence $matches is not set (even if it is magic). The underlying problem though is the download failure of the first history page that causes the alternative code path to execute at all, I'm not sure how to deal with filehippo in the face of "random" closed connections.

**Comment by pascalberger** [comment]
Package seems now to be hosted in https://github.com/niks255/ChocolateyPackages/tree/master/foobar2000 and was updated
