### ISSUE TITLE
Notes on changing Skype package for newer releases

### ISSUE THREAD

**Issue by teknowledgist** [ferventcoder/chocolatey-packages#278]
I'm not versed in Ketarin to make PRs for the Skype package, but I've poked at the newer version.  I thought I would jot my notes here for whomever eventually updates/takes over the package...

* Download link for new versions:  https://go.skype.com/windows.desktop.download
* The download is of the regex form `Skype-([0-9][0-9.]+)\.exe` with the version as `\1`.  It is v8.18.0.6 at this moment.
* The installer must be run in compatibility mode in Windows 10 because otherwise it will stop and insist the install must come from the "Store" as a "modern app" (UWP).  Compatibility can be set via: `REG ADD "HKLM\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /V <local path to SkypeInstaller.exe> /T REG_SZ /D WIN7RTM /F` or the PowerShell equivalent.  I am pretty sure the Win8 compatibility (`WIN8RTM`) works here too.
* Once installed, the new (non-UWP) version runs fine in Win10.
* The installer is silent with switches: `/sp- /verysilent /norestart` but I have not been able to disable:
    * the desktop icon
    * Skype starting after install
    I have (blindly) tried:  `/nodesktopicon`, `/noicons`, `/MERGETASKS="removedesktopicon"`, `/MERGETASKS="!desktopicon"`, `/MERGETASKS="!startskype"` all to no effect.  Someone smarter than I probably knows how to discover the tasks to include in the `/MERGETASKS=` command.  (I'm sure that is where the magic is.)

Hope this helps.

**Comment by gep13** [comment]
@jberezanski am I right in saying that this can be closed?

**Comment by jberezanski** [comment]
Yes, I believe so. I'd like the `skype` package to remain on 7.x for as long as possible, because Skype 8.x is... *inferior*, in my opinion (it is virtually a new application, lacking many features of the earlier versions). I think releasing 8.x on chocolatey.org would warrant a new package id (and if someone would want to do it, these notes would probably help).

**Comment by jberezanski** [comment]
> releasing 8.x on chocolatey.org would warrant a new package id

On second thought, perhaps not, because 8.x would replace 7.x, so from packaging standpoint it should be the same package. However, I would not publish 8.x at all until choco.exe learns how to [pin a package to a version range](https://github.com/chocolatey/choco/issues/1278) (so that all interested users would be able to pin skype to 7.x).

**Comment by gep13** [comment]
This package is now being maintained here:

https://github.com/chocolatey/chocolatey-coreteampackages

So going to close this out.
