### ISSUE TITLE
poshgit install issue

### ISSUE THREAD

**Issue by dahlbyk** [ferventcoder/chocolatey-packages#41]
Installing posh-git produces the error below. As a workaround, you can run `C:\tools\poshgit\install.ps1` directly. **Make sure your [execution policy](https://technet.microsoft.com/library/hh847748.aspx) is at least `RemoteSigned`.** See [posh-git manual install instructions](https://github.com/dahlbyk/posh-git/blob/master/readme.md#installing-manual) for more details.

```
C:\tools\poshgit
poshgit has finished successfully! The chocolatey gods have answered your request!

Write-Error : poshgit did not finish successfully. Boo to the chocolatey gods!

[ERROR] Unable to index into an object of type System.IO.DirectoryInfo.

At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-ChocolateyFailure.ps1:30 char:14
+ Write-Error <<<< $errorMessage
+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

Write-Error : Package 'poshgit v0.5.0.201401009' did not install successfully: Unable to index into an object of type System.IO.DirectoryInfo.

At C:\ProgramData\chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:90 char:28

Write-Error <<<< "Package '$installedPackageName v$installedPackageVersion' did not install successfully: $($_.Exception.Message)"

CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException

FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error
Finished installing 'poshgit' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
```

**Comment by wolf99** [comment]
I get an error when attempting this: "The term 'install.ps1' is not recognised..." The only thing in the specified directory is dahlbyk-posh-git-869d4c5

**Comment by dahlbyk** [comment]
> I get an error when attempting this: "The term 'install.ps1' is not recognised..." The only thing in the specified directory is dahlbyk-posh-git-869d4c5

Not sure how I missed this - it should work if you `cd` into that directory.

**Comment by OswaldGlinkmeyer** [comment]
Got same issue as OP.  Followed various threads to end up here.  Tried to use install.ps1 but get message "It seems posh-git is already installed..."  Huh? Ok, I figure I need to start over, so I attempt "cuninst poshgit" but it says "poshgit is not installed. Cannot uninstall an non-existent package."

**Comment by OswaldGlinkmeyer** [comment]
I should also report that despite Chocolately not knowing if poshgit is installed or not, poshgit does appear to be working now.

**Comment by jbgps** [comment]
I just went through this problem, in which poshgit install failed using "cinst poshgit" and failed again trying to directly run ".\install.ps1" from the "c:\tools\poshgit\dahlby##### folder."  The error generated by running ".\install.ps1" indicated running scripts was disabled on my system, and I should see "get-help about_signing".  I typed that command at the PS prompt and got a page on "about-signing."  From that help, the next step was guided by the "TO PERMIT SIGNED SCRIPTS TO RUN:" I ran: "get-executionpolicy" to find that my shell was RESTRICTED, so I ran "set-executionpolicy remotesigned", but that failed because I wasn't running the Powershell elevated.  To get the Powershell to run Elevated (as Admin) you type "start-process powershell -Verb runAs" from your existing non-elevate PS prompt, which launched another Powershell window as Elevated.  From there, you run the "set-executionpolicy remotesigned" command again (should work), and then, with the policy set to RemoteSigned I was able to go back to "tools\poshgit\dahlby###" and run ".\install.ps1" successfully (or at least that what it indicated).  

The key was that my Powershell policy wasn't enabled for Remotely Signed scripts.  Once that was done I didn't even need the elevated PS to run .\install.ps1.

I'm an old Unix guy but haven't played with Powershell, so this was new to me.  Maybe it'll expedite someone else.

**Comment by dahlbyk** [comment]
I suppose Chocolatey internally runs install scripts with an elevated execution policy?

For others' reference while this is finally resolved, here's the full guide to a manual install (exec policy is step 2): https://github.com/dahlbyk/posh-git/blob/master/readme.md#installing-manual.

**Comment by jbgps** [comment]
No, I think the issue for me was that I was running a PS install script in an environment that needed RemoteSigned execution policy but, since I hadn't been doing any PS work, my policy was set to Restricted.  I had to jump through a couple hoops to get the execution policy enabled for RemoteSigned scripts (which I assume your script was) before I could go back and run it using cinst, or in this case by directly running install.ps1.    My note probably only deals with people that haven't set the proper execution policy for PowerShell.  My guess is running chocolately elevated doesn't override the PS policy restrictions, though maybe there's a command line option to do that.  

The PS policy problem was not specified by the error message generated when trying to run "cinst" - it generates the System.IO.DirectoryInfo error.  Running your script seemed to provide the better indication of my problem: lack of proper PS script execution policy (RemoteSigned).

**Comment by dahlbyk** [comment]
I guess my thought is that since the typical Chocolatey install uses `@powershell -ExecutionPolicy Bypass ...` it's possible to get posh-git all the way installed without needing to `Set-ExecutionPolicy` such that the generated `$PROFILE` will actually run. That seems like something we might be able to at least warn about in our Chocolatey installer.

**Comment by jbgps** [comment]
Seems like bypassing the policy restriction silently would save the user
a lot of trouble. Hope it works. 

On 2015-05-24 20:24, Keith Dahlby wrote: 

> I guess my thought is that since the typical Chocolatey install uses @powershell -ExecutionPolicy Bypass ... it's possible to get posh-git all the way installed without needing to Set-ExecutionPolicy such that the generated $PROFILE will actually run. That seems like something we might be able to at least warn about in our Chocolatey installer. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/ferventcoder/chocolatey-packages/issues/41#issuecomment-105094670

**Comment by dahlbyk** [comment]
> Seems like bypassing the policy restriction silently would save the user a lot of trouble.

Created https://github.com/dahlbyk/posh-git/issues/196 to see if we can improve that experience.

**Comment by ferventcoder** [comment]
So Posh-Git package has moved to the official posh-git repo. I'm going to close this issue over here. If you are still experiencing issues with it once the new version of the package is released, please followup at https://github.com/dahlbyk/posh-git :)

**Comment by dahlbyk** [comment]
In https://github.com/dahlbyk/posh-git/issues/166, more specifically.
